//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Allowance.java
//  @ Date : 09-04-2010
//  @ Author : 
//
//

package com.sony.travelRequest.model;

public class Allowance {
	//private TravelRequest travelRequest;
	private float airportTransport;
	private float dailyAllowance;
	private float conveyance;
	private float days;
	private float otherAllowance;
	private String otherAllowanceDetail;
	private String currency;
	
	public Allowance()
	{
		airportTransport=50;
		conveyance=10;
		days=20;
	}
	
	public float getOtherAllowance() {
		return otherAllowance;
	}
	public void setOtherAllowance(float otherAllowance) {
		this.otherAllowance = otherAllowance;
	}
	
	public String getOtherAllowanceDetail() {
		return otherAllowanceDetail;
	}
	public void setOtherAllowanceDetail(String otherAllowanceDetail) {
		this.otherAllowanceDetail=otherAllowanceDetail;
	}
	
	public String getCurrency() {
		return currency;
	}
	public void setCurrency(String currency) {
		this.currency=currency;
	}
	public float getAirportTransport() {
		return airportTransport;
	}
	public void setAirportTransport(float airportTransport) {
		this.airportTransport = airportTransport;
	}
	public float getDailyAllowance() {
		return dailyAllowance;
	}
	public void setDailyAllowance(float dailyAllowance) {
		this.dailyAllowance = dailyAllowance;
	}
	public float getConveyance() {
		return conveyance;
	}
	public void setConveyance(float conveyance) {
		this.conveyance = conveyance;
	}
	public float getDays() {
		return days;
	}
	public void setDays(float days) {
		this.days = days;
	}
	
}
