//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Allowance.java
//  @ Date : 09-04-2010
//  @ Author : 
//
//

package com.sony.travelRequest.model;

public class Allowance {
	
	private float perDayAllowance;
	private float dailyAllowance;
	private float miscAllowance;
	private float days;
	
	public float getPerDayAllowance() {
		return perDayAllowance;
	}
	public void setPerDayAllowance(float perDayAllowance) {
		this.perDayAllowance = perDayAllowance;
	}
	public float getDailyAllowance() {
		return dailyAllowance;
	}
	public void setDailyAllowance(float dailyAllowance) {
		this.dailyAllowance = dailyAllowance;
	}
	public float getMiscAllowance() {
		return miscAllowance;
	}
	public void setMiscAllowance(float miscAllowance) {
		this.miscAllowance = miscAllowance;
	}
	public float getDays() {
		return days;
	}
	public void setDays(float days) {
		this.days = days;
	}
	
}
