//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : ApprovalProcessor.java
//  @ Date : 09-04-2010
//  @ Author : 
//
//

package com.sony.travelRequest.model;


public class ApprovalProcessor {
	
	public void accept() {
	
	}
	
	public void reject() {
	
	}
	
	public void sendMail() {
	
	}
	
}
