//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Email.java
//  @ Date : 09-04-2010
//  @ Author : 
//
//

package com.sony.travelRequest.model;


public class Email {
	
	private String sender;
	private String recepient;
	private String subject;
	private String body;
	
	public String getSender() {
		return sender;
	}

	public void setSender(String sender) {
		this.sender = sender;
	}

	public String getRecepient() {
		return recepient;
	}

	public void setRecepient(String recepient) {
		this.recepient = recepient;
	}

	public String getSubject() {
		return subject;
	}

	public void setSubject(String subject) {
		this.subject = subject;
	}

	public String getBody() {
		return body;
	}

	public void setBody(String body) {
		this.body = body;
	}

	public String getBodyForEmployeeTravelRequest() {
		return null;
	}
	
	public String getBodyForInitiatorTravelRequest() {
		return null;
	}
	
	public String getBodyForTravelDeskTravelRequest() {
		return null;
	}
	
	public String getBodyForRecommendedTravelRequest() {
		return null;
	}
	
	public String getBodyForAuthorisedTravelRequest() {
		return null;
	}
}
