//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : HotelResv.java
//  @ Date : 09-04-2010
//  @ Author : 
//
//

package com.sony.travelRequest.model;

import java.util.Date;


public class HotelResv {
	
	private String place;
	private String name;
	private Date checkIn;
	private Date checkOut;
	private float amountPerDay;
	private float amount;
	private float amountINR;
	
	public String getPlace() {
		return place;
	}
	public void setPlace(String place) {
		this.place = place;
	}
	public String getName() {
		return name;
	}
	public void setName(String name) {
		this.name = name;
	}
	public Date getCheckIn() {
		return checkIn;
	}
	public void setCheckIn(Date checkIn) {
		this.checkIn = checkIn;
	}
	public Date getCheckOut() {
		return checkOut;
	}
	public void setCheckOut(Date checkOut) {
		this.checkOut = checkOut;
	}
	public float getAmount() {
		return amount;
	}
	public void setAmount(float amount) {
		this.amount = amount;
	}
	public float getAmountINR() {
		return amountINR;
	}
	public void setAmountINR(float amountINR) {
		this.amountINR = amountINR;
	}
	public float getAmountPerDay() {
		return amountPerDay;
	}
	public void setAmountPerDay(float amountPerDay) {
		this.amountPerDay = amountPerDay;
	}

}
