//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : TravelResv.java
//  @ Date : 09-04-2010
//  @ Author : 
//
//

package com.sony.travelRequest.model;

import java.util.Calendar;
import java.util.Date;

import javax.faces.event.AbortProcessingException;
import javax.faces.event.ValueChangeEvent;
import javax.faces.model.SelectItem;
import org.hibernate.validator.Email;

import org.hibernate.validator.Length;

import org.hibernate.validator.Max;

import org.hibernate.validator.Min;

import org.hibernate.validator.NotEmpty;

import org.hibernate.validator.NotNull;

import org.hibernate.validator.Pattern;


public class TravelResv {
	//@NotEmpty
	private Date travelDate;
	//@NotEmpty
	private String travelFrom;
	//@NotEmpty
	private String travelTo;
	private String modeType;
	private String classType;
	//@NotEmpty
	private String depTime;
	//@NotEmpty
	private String arrTime;
	//@NotNull
	@Min(0)
	private float amount;
	
	public TravelResv() {
		Calendar cal = Calendar.getInstance();
		cal.add(Calendar.DATE, 2);
		this.travelDate = cal.getTime();
	}
	
	public Date getTravelDate() {
		return travelDate;
	}
	public void setTravelDate(Date travelDate) {
		this.travelDate = travelDate;
	}
	public String getTravelFrom() {
		return travelFrom;
	}
	public void setTravelFrom(String travelFrom) {
		this.travelFrom = travelFrom;
	}
	public String getTravelTo() {
		return travelTo;
	}
	public void setTravelTo(String travelTo) {
		this.travelTo = travelTo;
	}
	public String getModeType() {
		return modeType;
	}
	public void setModeType(String modeType) {
		this.modeType = modeType;
	}
	public String getClassType() {
		return classType;
	}
	public void setClassType(String classType) {
		this.classType = classType;
	}
	public String getDepTime() {
		return depTime;
	}
	public void setDepTime(String depTime) {
		this.depTime = depTime;
	}
	public String getArrTime() {
		return arrTime;
	}
	public void setArrTime(String arrTime) {
		this.arrTime = arrTime;
	}
	public float getAmount() {
		return amount;
	}
	public void setAmount(float amount) {
		this.amount = amount;
	}

}
