//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : TravelDetails.java
//  @ Date : 09-04-2010
//  @ Author : 
//
//

package com.sony.travelRequest.model;

import java.util.Calendar;
import java.util.Date;


public class TravelDetails {
	
	private String purpose;
	private Date startDate;
	private Date endDate;
	private String recommndedEmpMailId;
	private String authorisedEmpMailId;
	private Allowance allowance = new Allowance();
	
	public TravelDetails() {
		Calendar cal = Calendar.getInstance();
		cal.add(Calendar.DATE, 2);
		this.startDate = cal.getTime();
		cal.add(Calendar.DATE, 20);
		this.endDate = cal.getTime();
	}
	
	public String getPurpose() {
		return purpose;
	}
	public void setPurpose(String purpose) {
		this.purpose = purpose;
	}
	public Date getStartDate() {
		return startDate;
	}
	public void setStartDate(Date startDate) {
		this.startDate = startDate;
	}
	public Date getEndDate() {
		return endDate;
	}
	public void setEndDate(Date endDate) {
		this.endDate = endDate;
	}
	public String getRecommndedEmpMailId() {
		return recommndedEmpMailId;
	}
	public void setRecommndedEmpMailId(String recommndedEmpMailId) {
		this.recommndedEmpMailId = recommndedEmpMailId;
	}
	public String getAuthorisedEmpMailId() {
		return authorisedEmpMailId;
	}
	public void setAuthorisedEmpMailId(String authorisedEmpMailId) {
		this.authorisedEmpMailId = authorisedEmpMailId;
	}
	public Allowance getAllowance() {
		return allowance;
	}
	public void setAllowance(Allowance allowance) {
		this.allowance = allowance;
	}
	
}
