//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : EmailComponent.java
//  @ Date : 09-04-2010
//  @ Author : 
//
//

package com.sony.travelRequest.util;

import java.util.List;
import org.springframework.mail.SimpleMailMessage;
import org.springframework.mail.javamail.JavaMailSender;

public class EmailComponent {

	private JavaMailSender mailSender;

	public JavaMailSender getMailSender() {
		return mailSender;
	}

	public void setMailSender(JavaMailSender mailSender) {
		this.mailSender = mailSender;
	}

	public void sendMails(List<String> recepients,
			String subject, String body) {
		for (String recepient : recepients) {
			SimpleMailMessage simpleMailMessage = new SimpleMailMessage();
			simpleMailMessage.setTo(recepient);
			simpleMailMessage
					.setSubject("Travel Request: "
							+ subject);
			StringBuilder buf = new StringBuilder(256);
			buf.append(body);
			simpleMailMessage.setText(buf.toString());
			try {
				this.mailSender.send(simpleMailMessage);
			} catch (Exception e) {
				e.printStackTrace();
				System.out.println("error");
			}
		}
	}

}
